version = 0.1

[default.deploy.parameters]
stack_name = "back-end"
resolve_s3 = true
s3_prefix = "back-end"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "BucketPrefix=\"cloud-resume-visitor-logs\" DeliveryStreamName=\"cloud-resume-visitor-log-stream\" CompressionFormat=\"UNCOMPRESSED\" BufferingIntervalInSeconds=\"300\" BufferingSizeInMBs=\"5\" DynamoTableName=\"cloud-resume-visitor-logs\""
image_repositories = []

[default.global.parameters]
region = "eu-central-1"
